import { Category, Product, ConsultationRecord, OrderRecord } from "./types";

export const MOCK_CATEGORIES: Category[] = [
  { id: 1, name_en: "Oils", name_ur: "روغن", slug: "oils" },
  { id: 2, name_en: "Hair Care", name_ur: "بالوں کی دیکھ بھال", slug: "hair-care" },
  { id: 3, name_en: "Skin Care", name_ur: "جلد کی دیکھ بھال", slug: "skin-care" },
  { id: 4, name_en: "Men's Health", name_ur: "مردانہ صحت", slug: "mens-health" },
  { id: 5, name_en: "Diabetes Support", name_ur: "ذیابطیس کی دیکھ بھال", slug: "diabetes-support" },
  { id: 6, name_en: "Kids Nutrition", name_ur: "بچوں کی نشوونما", slug: "kids-nutrition" },
  { id: 7, name_en: "Digestive Relief", name_ur: "ہضم اور معدہ", slug: "digestive-relief" },
  { id: 8, name_en: "Weight Gain", name_ur: "وزن میں اضافہ", slug: "weight-gain" },
  { id: 9, name_en: "Pain Relief", name_ur: "درد کا علاج", slug: "pain-relief" },
  { id: 10, name_en: "Weight Loss", name_ur: "وزن کی کمی", slug: "weight-loss" },
  { id: 11, name_en: "Women's Health", name_ur: "خواتین کی صحت", slug: "womens-health" },
  { id: 12, name_en: "Unani Majoons", name_ur: "معجونات", slug: "unani-majoons" },
  { id: 13, name_en: "Sharbat & Distillates", name_ur: "شربت اور عرق", slug: "sharbat-arq" },
  { id: 14, name_en: "Preserves & Murabba", name_ur: "مربہ جات", slug: "murabba" },
  { id: 15, name_en: "Spices & Condiments", name_ur: "مصالحہ جات", slug: "spices" },
  { id: 16, name_en: "Dry Fruits & Nuts", name_ur: "میوہ جات", slug: "dry-fruits" },
  { id: 17, name_en: "Raw Herbs", name_ur: "جڑی بوٹیاں", slug: "raw-herbs" }
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    category_id: 1,
    brand: "Hi Herbs",
    name_en: "Onion Hair Oil",
    name_ur: "پیاز کا تیل",
    slug: "onion-hair-oil",
    sku: "HH-OIL-01",
    description: "For strong, healthy hair growth — made with red onion extract & 10 natural oils.",
    benefits: "• Stimulates scalp blood circulation\n• Prevents excessive hair fall\n• Nourishes hair follicles from root to tip",
    how_to_use: "Apply gently on scalp twice a week before bed. Rinse next morning.",
    ingredients: "Red Onion Extract, Virgin Coconut Oil, Almond Oil, Sesame Oil, Vitamin E.",
    price: 250,
    weight_options_json: [
      { label: "30 ml", price: 250 },
      { label: "100 ml", price: 600 }
    ],
    stock_quantity: 150,
    images_json: ["/WebsiteData/IMG_6354.PNG"],
    is_featured: true,
    category_name: "Oils"
  },
  {
    id: 2,
    category_id: 1,
    brand: "Hi Herbs",
    name_en: "Sarsoo Oil (Mustard Oil)",
    name_ur: "سرسوں کا خالص تیل",
    slug: "mustard-oil-sarsoo",
    sku: "HH-OIL-02",
    description: "100% pure & cold-pressed natural mustard oil.",
    benefits: "• Rich in Omega-3 & Omega-6 fatty acids\n• Excellent for body massage and hair conditioning\n• Pure unrefined extraction",
    how_to_use: "Warm slightly and massage onto body joints or hair scalp.",
    ingredients: "100% Cold Pressed Mustard Seeds.",
    price: 600,
    weight_options_json: [
      { label: "1 Litre", price: 600 },
      { label: "500 ml", price: 320 }
    ],
    stock_quantity: 200,
    images_json: ["/placeholder-oil.png"],
    is_featured: false,
    category_name: "Oils"
  },
  {
    id: 3,
    category_id: 1,
    brand: "Hi Herbs",
    name_en: "Retha & Dhaniya Hair Oil",
    name_ur: "ریٹھا دھنیا تیل",
    slug: "retha-dhaniya-hair-oil",
    sku: "HH-OIL-03",
    description: "For revitalized scalp health — made with retha, dhaniya oil & natural botanicals.",
    benefits: "• Soothes irritated scalp and relieves itchiness\n• Strengthens hair shaft\n• Imparts natural herbal sheen",
    how_to_use: "Massage into scalp 30 minutes before washing.",
    ingredients: "Retha Extract, Coriander Oil, Sesame Oil Base.",
    price: 300,
    weight_options_json: [{ label: "250 gms", price: 300 }],
    stock_quantity: 80,
    images_json: ["/placeholder-oil.png"],
    is_featured: false,
    category_name: "Oils"
  },
  {
    id: 4,
    category_id: 1,
    brand: "Hi Herbs",
    name_en: "Rosemary Hair Oil",
    name_ur: "روزمیری آئل",
    slug: "rosemary-hair-oil",
    sku: "HH-OIL-04",
    description: "For revitalized, thick hair growth — pure essential rosemary blend.",
    benefits: "• Clinically known to reactivate hair follicles\n• Prevents premature graying\n• Enhances hair volume",
    how_to_use: "Apply 3-4 drops directly to scalp and massage daily.",
    ingredients: "Pure Rosemary Oil, Jojoba Oil Base.",
    price: 120,
    weight_options_json: [{ label: "50 gms", price: 120 }],
    stock_quantity: 100,
    images_json: ["/placeholder-oil.png"],
    is_featured: true,
    category_name: "Oils"
  },
  {
    id: 5,
    category_id: 1,
    brand: "Hi Herbs",
    name_en: "Coconut Hair Oil",
    name_ur: "ناریل کا تیل",
    slug: "coconut-hair-oil",
    sku: "HH-OIL-05",
    description: "For nourished, shiny hair — made with pure coconut oil.",
    benefits: "• Locks in hair moisture\n• Prevents split ends\n• Natural sun protection for hair",
    how_to_use: "Apply generous amount 1 hour before shampooing.",
    ingredients: "100% Pure Virgin Coconut Oil.",
    price: 400,
    weight_options_json: [{ label: "250 gms", price: 400 }],
    stock_quantity: 150,
    images_json: ["/placeholder-oil.png"],
    is_featured: false,
    category_name: "Oils"
  },
  {
    id: 6,
    category_id: 2,
    brand: "Hi Herbs",
    name_en: "Flora Roots Herbal Hair Oil",
    name_ur: "فلورا روٹس ہربل آئل",
    slug: "flora-roots-herbal-hair-oil",
    sku: "HH-HC-01",
    description: "\"The Essence of Strength\" — 100% natural herbal hair oil for stronger roots.",
    benefits: "• 100% natural formulation\n• Deeply roots hair follicles\n• Protects against harsh environmental pollutants",
    how_to_use: "Massage gently into scalp using fingertips for 10 minutes.",
    ingredients: "Amla, Reetha, Shikakai, Rosemary, Bhringraj, Virgin Coconut Oil.",
    price: 699,
    weight_options_json: [{ label: "150 ml", price: 699 }],
    stock_quantity: 120,
    images_json: ["/WebsiteData/IMG_6355.PNG"],
    is_featured: true,
    category_name: "Hair Care"
  },
  {
    id: 7,
    category_id: 2,
    brand: "Hi Herbs",
    name_en: "Flora Roots Herbal Shampoo",
    name_ur: "فلورا روٹس ہربل شیمپو",
    slug: "flora-roots-herbal-shampoo",
    sku: "HH-HC-02",
    description: "\"The Natural Path to Luminous Hair\" — 100% natural, paraben-free herbal shampoo.",
    benefits: "• Paraben-free & Sulfate-free\n• Maintains natural scalp pH\n• Leaves hair silky and manageable",
    how_to_use: "Apply to wet hair, work into lather, rinse thoroughly.",
    ingredients: "Amla, Reetha, Shikakai, Aloe Vera Extract, Soft Cleansing Base.",
    price: 250,
    weight_options_json: [{ label: "150 ml", price: 250 }],
    stock_quantity: 140,
    images_json: ["/placeholder-shampoo.png"],
    is_featured: false,
    category_name: "Hair Care"
  },
  {
    id: 8,
    category_id: 4,
    brand: "Hi Herbs Naturals",
    name_en: "Men's Fertility Health Capsules",
    name_ur: "مردانہ طاقت کیپسول",
    slug: "mens-fertility-health-capsules",
    sku: "HH-MH-01",
    description: "100% botanical formulation designed for male well-being and reproductive vigor.",
    benefits: "• Enhances natural stamina and endurance\n• Supports male reproductive health\n• Promotes daily energy and vitality",
    how_to_use: "Take 1 capsule twice daily after meals with milk.",
    ingredients: "Salab Misri, Ashwagandha, Safed Musli, Zafran, Shilajit.",
    price: 1000,
    weight_options_json: [{ label: "60 Capsules / 100g", price: 1000 }],
    stock_quantity: 80,
    images_json: ["/WebsiteData/IMG_6356.PNG"],
    is_featured: true,
    category_name: "Men's Health"
  },
  {
    id: 9,
    category_id: 5,
    brand: "DiaCure",
    name_en: "DiaCure Naturals — Diabetes Support",
    name_ur: "ڈائیا کیور شوگر سپورٹ",
    slug: "diacure-naturals-diabetes-support",
    sku: "HH-DC-01",
    description: "Advanced blood sugar management blend; supports healthy insulin function.",
    benefits: "• Helps maintain healthy blood glucose levels\n• Supports pancreatic cellular health\n• Reduces frequent sugar cravings",
    how_to_use: "1 capsule twice daily 30 minutes before meals.",
    ingredients: "Karela Extract, Jamun Seed Powder, Gurmar, Methi Seed.",
    price: 500,
    weight_options_json: [{ label: "60 Capsules", price: 500 }],
    stock_quantity: 90,
    images_json: ["/WebsiteData/IMG_6357.PNG"],
    is_featured: true,
    category_name: "Diabetes Support"
  },
  {
    id: 10,
    category_id: 6,
    brand: "Hi Herbs",
    name_en: "Hi Herbs Talbina Powder",
    name_ur: "تلبینہ پاؤڈر",
    slug: "hi-herbs-talbina-powder",
    sku: "HH-KN-01",
    description: "For kids' growth — enriched with pure barley, nutrient-dense natural nourishment.",
    benefits: "• Sunnah recommended nutritional tonic\n• Rich in dietary fiber and essential minerals\n• Enhances physical growth and immune defense",
    how_to_use: "Cook 2 tbsp in milk for 10 minutes, sweeten with honey.",
    ingredients: "Pure Roasted Barley Flour, Honey Powder, Cardamom.",
    price: 1000,
    weight_options_json: [{ label: "500 gms", price: 1000 }],
    stock_quantity: 100,
    images_json: ["/WebsiteData/IMG_6358.PNG"],
    is_featured: true,
    category_name: "Kids Nutrition"
  },
  {
    id: 11,
    category_id: 7,
    brand: "Hi Herbs",
    name_en: "AciCalm Heartburn Relief Liquid",
    name_ur: "ایسی کام لیکوڈ",
    slug: "acicalm-heartburn-relief-liquid",
    sku: "HH-DR-01",
    description: "Forms a protective soothing barrier with ginger & marshmallow to calm reflux.",
    benefits: "• Rapid relief from acidity and acid reflux\n• Soothes lining of esophagus and stomach\n• Pure natural herbal mint flavor",
    how_to_use: "Take 10ml to 15ml after meals or whenever heartburn occurs.",
    ingredients: "Ginger Root Extract, Marshmallow Root, Peppermint Oil, Natural Mineral Salt Buffer.",
    price: 150,
    weight_options_json: [{ label: "150 ml", price: 150 }],
    stock_quantity: 200,
    images_json: ["/WebsiteData/IMG_6359.PNG"],
    is_featured: true,
    category_name: "Digestive Relief"
  },
  {
    id: 12,
    category_id: 9,
    brand: "PainRoot",
    name_en: "PainRoot Naturals — Joint & Muscle",
    name_ur: "پین روٹ جوڑوں کا علاج",
    slug: "painroot-naturals-joint-muscle",
    sku: "HH-PR-01",
    description: "Targets joint pain, supports flexibility, aids rapid muscle recovery with GoldenRoot.",
    benefits: "• Reduces joint stiffness and inflammation\n• Enhances joint mobility and cartilage strength\n• Fast recovery for active muscles",
    how_to_use: "Take 1 capsule daily after breakfast with warm water.",
    ingredients: "Golden Root Extract, Suranjan Shirin, Guggul, Turmeric Curcumin.",
    price: 200,
    weight_options_json: [{ label: "12 Golden Capsules", price: 200 }],
    stock_quantity: 110,
    images_json: ["/placeholder-capsule.png"],
    is_featured: true,
    category_name: "Pain Relief"
  },
  {
    id: 13,
    category_id: 14,
    brand: "Hi Herbs",
    name_en: "Murabba Amla",
    name_ur: "مربہ آملہ",
    slug: "murabba-amla",
    sku: "HH-MB-01",
    description: "Rich in Vitamin C; supports digestion, immunity, stamina, and eye health.",
    benefits: "• High Vitamin C antioxidant content\n• Promotes digestive vitality\n• Traditional memory and sight preserver",
    how_to_use: "Eat 1-2 pieces every morning on an empty stomach.",
    ingredients: "Fresh Amla Fruits, Pure Sugar Syrup, Silver Leaf Accent.",
    price: 800,
    weight_options_json: [
      { label: "1 kg", price: 800 },
      { label: "500 gms", price: 450 }
    ],
    stock_quantity: 100,
    images_json: ["/placeholder-jar.png"],
    is_featured: true,
    category_name: "Preserves & Murabba"
  },
  {
    id: 14,
    category_id: 16,
    brand: "Hi Herbs",
    name_en: "Almonds (Desi Badam)",
    name_ur: "دیسی بادام گری",
    slug: "desi-badam-almonds",
    sku: "HH-DF-01",
    description: "Whole desi almond kernels; traditional brain and general stamina tonic.",
    benefits: "• Rich in Healthy Fats & Protein\n• Boosts brain function and sharpens memory\n• Sustained physical energy",
    how_to_use: "Soak 7-10 almonds overnight in clean water and consume after peeling.",
    ingredients: "100% Pure Desi Almond Kernels.",
    price: 750,
    weight_options_json: [
      { label: "250g", price: 750 },
      { label: "1 kg", price: 2800 }
    ],
    stock_quantity: 200,
    images_json: ["/placeholder-nuts.png"],
    is_featured: true,
    category_name: "Dry Fruits & Nuts"
  },
  {
    id: 15,
    category_id: 17,
    brand: "Hi Herbs",
    name_en: "Saffron (Kesar / Zafran)",
    name_ur: "خالص زعفران",
    slug: "saffron-kesar-zafran",
    sku: "HH-RH-01",
    description: "Prized aromatic herb; mood, skin glow, and reproductive vitality tonic.",
    benefits: "• 100% Pure authentic stigma threads\n• Imparts natural golden hue and fragrance\n• Natural mood uplifter and tonic",
    how_to_use: "Steep 3-4 strands in warm milk or tea for 10 minutes before drinking.",
    ingredients: "100% Pure Kashmiri Saffron Stigmas.",
    price: 450,
    weight_options_json: [
      { label: "1g", price: 450 },
      { label: "5g", price: 2100 }
    ],
    stock_quantity: 50,
    images_json: ["/placeholder-saffron.png"],
    is_featured: true,
    category_name: "Raw Herbs"
  }
];

export const MOCK_ORDERS: OrderRecord[] = [
  {
    id: 1,
    order_number: "HIP-10492",
    customer_name: "Imran Khan",
    phone: "0300-1234567",
    whatsapp_number: "0300-1234567",
    email: "imran@example.com",
    shipping_address: "House 14, Block B, Gulberg III",
    city: "Lahore",
    payment_method: "COD",
    order_status: "Pending",
    subtotal: 2050,
    shipping_fee: 0,
    grand_total: 2050,
    notes: "Please call before delivery",
    created_at: "2026-09-05 14:30:00"
  },
  {
    id: 2,
    order_number: "HIP-10493",
    customer_name: "Ayesha Malik",
    phone: "0321-9876543",
    whatsapp_number: "0321-9876543",
    email: "ayesha@example.com",
    shipping_address: "Street 5, Sector F-7",
    city: "Islamabad",
    payment_method: "JazzCash",
    order_status: "Processing",
    subtotal: 1449,
    shipping_fee: 200,
    grand_total: 1649,
    notes: "Paid via JazzCash transaction ID 9482710492",
    created_at: "2026-09-06 09:15:00"
  }
];

export const MOCK_CONSULTATIONS: ConsultationRecord[] = [
  {
    id: 1,
    patient_name: "Muhammad Usman",
    phone: "0312-4545678",
    health_issue: "Hair Loss & Scalp Health",
    preferred_date: "2026-09-10",
    visit_type: "InClinic",
    status: "Confirmed",
    created_at: "2026-09-05 11:00:00"
  },
  {
    id: 2,
    patient_name: "Fatima Noor",
    phone: "0333-7654321",
    health_issue: "Acidity & Reflux Management",
    preferred_date: "2026-09-12",
    visit_type: "OnlineWhatsApp",
    status: "Pending",
    created_at: "2026-09-06 10:20:00"
  }
];
